import os
import subprocess
import logging
from typing import Any
from config import FFMPEG_PATH

logger = logging.getLogger(__name__)

class SadTalkerService:
    """
    Service for generating talking head videos using SadTalker.
    """
    def __init__(self, checkpoints_dir: str):
        self.checkpoints_dir = checkpoints_dir
        self.is_ready = self._check_weights()

    def _check_weights(self) -> bool:
        required_files = [
            "auido2exp.pth",
            "auido2pose.pth",
            "expression.mat",
            "face_vid2vid_256_v0.0.pth",
            "shape_predictor_68_face_landmarks.dat"
        ]
        missing = [f for f in required_files if not os.path.exists(os.path.join(self.checkpoints_dir, f))]
        if missing:
            logger.warning(f"Missing SadTalker weights: {missing}")
            # If we have the v0.0.2 safetensors, maybe we can use it?
            if os.path.exists(os.path.join(self.checkpoints_dir, "SadTalker_V0.0.2_256.safetensors")):
                logger.info("Found SadTalker_V0.0.2_256.safetensors, might be usable.")
            return False
        return True

    async def generate_video(self, photo_path: str, audio_path: str, output_path: str, job_id: str, job_manager: Any):
        """
        Runs the SadTalker inference using the real engine.
        """
        job_manager.update_job(job_id, status="processing", progress=10, message="Initializing SadTalker engine...")
        
        try:
            import sys
            # Paths
            sadtalker_root = os.path.join(os.path.dirname(os.path.dirname(__file__)), "sadtalker_new", "SadTalker-main")
            inference_script = os.path.join(sadtalker_root, "inference.py")
            result_dir = os.path.join(os.path.dirname(output_path), f"results_{job_id}")
            os.makedirs(result_dir, exist_ok=True)
            
            # Construct command
            # python inference.py --preprocess full --img_size 256 --source_image photo.jpg --driven_audio audio.wav
            cmd = [
                sys.executable, inference_script,
                "--source_image", photo_path,
                "--driven_audio", audio_path,
                "--checkpoint_dir", self.checkpoints_dir,
                "--result_dir", result_dir,
                "--preprocess", "full",
                "--enhancer", "gfpgan", # Ultra Realistic enhancement
                "--still" # Reduce body motion for more realism in still portraits
            ]
            
            logger.info(f"Running SadTalker command: {' '.join(cmd)}")
            job_manager.update_job(job_id, progress=20, message="SadTalker inference started...")
            
            # Run inference
            # We use a context manager or direct call. Since it's a script, subprocess is fine.
            process = subprocess.Popen(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                cwd=sadtalker_root
            )
            
            # Monitor progress (simplified)
            while True:
                if process.stdout:
                    line = process.stdout.readline()
                    if not line and process.poll() is not None:
                        break
                    if line:
                        logger.debug(f"SadTalker output: {line.strip()}")
                else:
                    if process.poll() is not None:
                        break
            
                # Update dummy progress
                job_manager.update_job(job_id, progress=50, message="Processing facial animation...")

            stdout, stderr = process.communicate()
            
            if process.returncode != 0:
                raise Exception(f"SadTalker failed with exit code {process.returncode}: {stderr}")

            # Find output video
            # SadTalker saves as result_dir/TIMESTAMP.mp4 or something similar
            video_files = [f for f in os.listdir(result_dir) if f.endswith(".mp4")]
            if not video_files:
                raise Exception("No output video generated by SadTalker")
            
            generated_video = os.path.join(result_dir, video_files[0])
            
            # Move to final output path
            import shutil
            shutil.move(generated_video, output_path)
            
            # Cleanup result dir
            shutil.rmtree(result_dir)
            
            job_manager.update_job(job_id, status="completed", progress=100, message="Ultra Realistic video generated!", result={"videoUrl": f"/outputs/{os.path.basename(output_path)}"})
            
        except Exception as e:
            logger.error(f"SadTalker error: {e}")
            job_manager.update_job(job_id, status="failed", error=str(e))
